[package]
name = "argpx_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]
name = "argpx_rs"

[dependencies]
enumflags2 = "0.7.10"
libc = "0.2.77"
thiserror = "2.0.11"


[build-dependencies]
cbindgen = "0.20"
