/* Copyright (C) 2025 Cyan Changes. */

#ifndef __ARGPX_RS
#define __ARGPX_RS

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>


void hello(void);

#endif /* __ARGPX_RS */
