name: Compile test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: ./configure.sh --enable-batch-alloc --debug
      - name: build
        run: mkdir build/ && make
      - name: build test
        working-directory: example/
        run: make
      - name: end-to-end test
        working-directory: example/
        run: ./test_e2e.sh
      - uses: actions/upload-artifact@v4
        with:
          name: test.out
          path: example/test.out
