name: Compile test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make
      - name: end-to-end test
        run: ./test_e2e.sh
      - uses: actions/upload-artifact@v4
        with:
          name: test.out
          path: example/test.out
